version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - db
    ports:
      - 8080:80

  db:
    platform: linux/x86_64
    image: mariadb
    restart: always
    ports:
      - 13306:3306
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    ports:
      - 8888:80
    depends_on:
      - db